# Generated by Django 2.2.3 on 2019-09-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_auto_20190905_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='update_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
